name: api-build

on:
    push:
        branches:
            - main
        paths:
            - 'github/workflows/api-build.yml'
            - 'app/**'
            - 'core/**'
            - 'routers/**'
            - 'tests/**'
            - 'requirements.txt'
            - 'Dockerfile'
            - 'run.py'

jobs:
    build:
        name: build-fastapi-api
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run FastAPI build checks
              run: |
                # Run all tests
                pytest tests/ -v
                
                # Test API can start
                python -c "from app.main import app; print('✅ App imports successfully')"