name: github-actions-demo

on:
  push:
    paths:
      - "./github/workflows/gh.yml"
  workflow_dispatch: # manual trigger

jobs:
  cli:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: env
      - run: gh --version
      - run: gh auth status
      - run: gh repo list
      - run: gh issue list
      - run: gh pr list
      - run: gh workflow list
      - run: gh repo view
      - run: gh app /repos/:owner/:repo/actions/workflows
